# Generated by Django 4.1.7 on 2023-04-05 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="CategoryProduct",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("category_id", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="products.category")),
                ("product_id", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="products.product")),
            ],
        ),
        migrations.AddField(
            model_name="category",
            name="product",
            field=models.ManyToManyField(
                related_name="categories", through="products.CategoryProduct", to="products.product"
            ),
        ),
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name_plural": "categories"},
        ),
        migrations.RenameField(
            model_name="category",
            old_name="product",
            new_name="products",
        ),
        migrations.CreateModel(
            name="Subcategory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=50, unique=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subcategories",
                        to="products.category",
                    ),
                ),
                ("products", models.ManyToManyField(related_name="subcategories", to="products.product")),
            ],
            options={
                "verbose_name_plural": "subcategories",
            },
        ),
    ]
